### ISSUE TITLE
[Bug] Refering to action with `@v<major>` does not work

### ISSUE THREAD

**Issue by o-l-a-v** [microsoft/psscriptanalyzer-action#15]
It's common to be able to refer to a major version only for GitHub Actions, so I expected the following to work, but it did not:

```yaml
 - name: Run PSScriptAnalyzer
   uses: microsoft/psscriptanalyzer-action@v1
   with:
    path: .\
    recurse: true 
    output: results.sarif
```

Resulted in: `Unable to resolve action 'microsoft/psscriptanalyzer-action@v1', unable to find version 'v1'`
