### ISSUE TITLE
[Feature] Example usage with changed files only on PR

### ISSUE THREAD

**Issue by o-l-a-v** [microsoft/psscriptanalyzer-action#16]
Would be very helpful with an example on how to lint changed and added files only in a PR.

I solved it by using following action to get added and changed files:

* <https://github.com/tj-actions/changed-files>

```yaml
- name: Get changed files 🔍
  id: get-changed-files
  uses: tj-actions/changed-files@v44
  with:
    files: "**.ps1"
    json: true
    write_output_files: true
```

Then I wrote a script that runs PSScriptAnalyzer, instead of using this action. Because I found it hard to give the `path:` parameter a format it accepted. Can't share my actual script as it's company IP, but here's how I picked up changed files inside the GitHub workflow and fed the paths to the script:

```yaml
- name: Lint with PSScriptAnalyzer 📃
  if: steps.get-changed-files.outputs.any_changed == 'true'
  shell: pwsh
  run: |
    # Collect paths of changed files
    $Files = [string[]](
        ConvertFrom-Json -InputObject (
            Get-Content -Raw -Path '.github/outputs/all_changed_and_modified_files.json'
        )
    )

    # Run script
    & ./Scripts/Workflows/Lint-PowerShell.ps1 -FilePaths $Files
```
