### ISSUE TITLE
[Feature] Accept input JSON file containing file paths

### ISSUE THREAD

**Issue by o-l-a-v** [microsoft/psscriptanalyzer-action#17]
Related to #16.

Would be sweet if `microsoft/psscriptanalyzer-action` could take a JSON file containing file paths as input. Then it'd be very easy to lint changed files only on PR, with a little something like:

```yaml
- name: GitHub checkout branch "${{ github.head_ref }}" 🛎️
  uses: actions/checkout@v4

- name: Get changed files 🔍
  id: get-changed-files
  uses: tj-actions/changed-files@v44
  with:
    files: "**.ps1"
    json: true
    write_output_files: true

- name: Run PSScriptAnalyzer
  if: steps.get-changed-files.outputs.any_changed == 'true'
  uses: microsoft/psscriptanalyzer-action@v1.1
  with:
   path: .github/outputs/all_changed_and_modified_files.json
   output: results.sarif
```

Or maybe a new input parameter for this scenario?
