### ISSUE TITLE
How to use in Github Action - Wrong Dokumentation

### ISSUE THREAD

**Issue by floriankoch** [microsoft/psscriptanalyzer-action#2]
Hi,

i try to use this in a GitHub Action 

This gives me a syntax error, because i need to specify the reference in the form 

org/repo/@version

The Generated Version from the Makretpace uses  the correct reference, but the Documentation is wrong
microsoft/psscriptanalyzer-action@v1.0

```

name: Powershell PSScriptAnalyzer CI

on:
  push:
    branches: [ develop ]


jobs:
  pwsh_ci:
    runs-on: windows-latest
    name: PSScriptAanalyzer
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: Run PSScriptAnalyzer
        uses: -psscriptanalyzer-action
        with:
          path: .\
          recurse: true 
          output: results.sarif
```
