### ISSUE TITLE
Bad link referenced in Readme.md

### ISSUE THREAD

**Issue by schapma-cic** [microsoft/psscriptanalyzer-action#6]
The follow section in the readMe contains a link that does not exist.

> Uses only the custom rules defined in the specified paths to the analysis. To still use the built-in rules, add the -IncludeDefaultRules switch. More info [here](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/docs/markdown/Invoke-ScriptAnalyzer.md#-includedefaultrules).

In addition, when you click to configure this action from GitHub for your repo, it defaults the below section in the yaml - however the link there (https://github.com/microsoft/action-psscriptanalyzer) also does not exist.

below snippet is from https://github.com/microsoft/psscriptanalyzer-action/blob/main/workflow.yml

```
        name: Run PSScriptAnalyzer
        uses: ./
        with:
          # Check https://github.com/microsoft/action-psscriptanalyzer for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          path: .\
          recurse: true 
```
